<?php
declare(strict_types=1);

namespace App\Mailer;

use App\Model\Entity\User;
use Cake\Mailer\Mailer;
use Cake\Mailer\Message;
use Cake\Routing\Router;

/**
 * User Mailer
 *
 * Transactional email for the admin accounts.
 */
class UserMailer extends Mailer
{
    /**
     * Mailer name.
     *
     * @var string
     */
    public static string $name = 'User';

    /**
     * Build the password reset email.
     *
     * The plain-text token only ever exists in transit: it is generated by the
     * controller, embedded in this link, and discarded. The database holds a
     * hash of it, so this email is the single copy of the usable secret.
     *
     * The link is absolute, which makes it depend on `App.fullBaseUrl`. That
     * value must be pinned in production (see config/app.php) so a forged Host
     * header cannot rewrite the link to point at an attacker's domain.
     *
     * @param \App\Model\Entity\User $user The account requesting the reset.
     * @param string $token The plain-text reset token.
     * @param int $expiresInHours How long the link stays valid, in hours.
     * @return void
     */
    public function resetPassword(User $user, string $token, int $expiresInHours): void
    {
        $resetUrl = Router::url(
            [
                'controller' => 'Users',
                'action' => 'resetPassword',
                $token,
            ],
            true,
        );

        $this
            ->setTo($user->email)
            ->setSubject(__('Reset your Eco Glow Lighting password'))
            ->setEmailFormat(Message::MESSAGE_BOTH)
            ->setViewVars([
                'resetUrl' => $resetUrl,
                'expiresInHours' => $expiresInHours,
            ]);

        $this->viewBuilder()->setTemplate('reset_password');
    }
}
