<?php
declare(strict_types=1);

namespace App\Mailer;

use App\Model\Entity\User;
use Cake\Mailer\Mailer;
use Cake\Mailer\Message;
use Cake\Routing\Router;

/**
 * User Mailer
 *
 * Transactional email for the admin accounts.
 */
class UserMailer extends Mailer
{
    /**
     * Mailer name.
     *
     * @var string
     */
    public static string $name = 'User';

    /**
     * Build the password reset email.
     *
     * The plain-text token only ever exists in transit: it is generated by the
     * controller, embedded in this link, and discarded. The database holds a
     * hash of it, so this email is the single copy of the usable secret.
     *
     * The link is absolute, which makes it depend on `App.fullBaseUrl`. That
     * value must be pinned in production (see config/app.php) so a forged Host
     * header cannot rewrite the link to point at an attacker's domain.
     *
     * @param \App\Model\Entity\User $user The account requesting the reset.
     * @param string $token The plain-text reset token.
     * @param int $expiresInHours How long the link stays valid, in hours.
     * @param bool $fromCustomer Whether the request started on the customer form.
     * @return void
     */
    public function resetPassword(
        User $user,
        string $token,
        int $expiresInHours,
        bool $fromCustomer = false,
    ): void {
        $url = [
            'controller' => 'Users',
            'action' => 'resetPassword',
            $token,
        ];
        if ($fromCustomer) {
            $url['?'] = ['from' => 'customer'];
        }
        $resetUrl = Router::url($url, true);

        $this
            ->setTo($user->email)
            ->setSubject(__('Reset your Eco Glow Lighting password'))
            ->setEmailFormat(Message::MESSAGE_BOTH)
            ->setViewVars([
                'resetUrl' => $resetUrl,
                'expiresInHours' => $expiresInHours,
            ]);

        $this->viewBuilder()->setTemplate('reset_password');
    }

    /**
     * @param \App\Model\Entity\User $user Account.
     * @param string $token Plain confirmation token.
     * @return void
     */
    public function verifyEmail(User $user, string $token): void
    {
        $url = Router::url(['controller' => 'Users', 'action' => 'verifyEmail', $token], true);
        $this
            ->setTo($user->email)
            ->setSubject(__('Confirm your Eco Glow Lighting email'))
            ->setEmailFormat(Message::MESSAGE_TEXT)
            ->setViewVars(['verifyUrl' => $url]);
        $this->viewBuilder()->setTemplate('verify_email');
    }

    /**
     * @param \App\Model\Entity\User $user Account.
     * @param string $newEmail Address being confirmed.
     * @param string $token Plain confirmation token.
     * @return void
     */
    public function confirmEmailChange(User $user, string $newEmail, string $token): void
    {
        $url = Router::url(['controller' => 'Account', 'action' => 'confirmEmail', $token], true);
        $this
            ->setTo($newEmail)
            ->setSubject(__('Confirm your new Eco Glow Lighting email'))
            ->setEmailFormat(Message::MESSAGE_TEXT)
            ->setViewVars(['verifyUrl' => $url, 'newEmail' => $newEmail]);
        $this->viewBuilder()->setTemplate('confirm_email_change');
    }
}
