-- Fresh-install definitions preserve every existing CakePHP field exactly.
CREATE TABLE `users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `password_reset_token` VARCHAR(255) NULL DEFAULT NULL,
    `password_reset_expires` DATETIME NULL DEFAULT NULL,
    `created` DATETIME NOT NULL,
    `modified` DATETIME NOT NULL,
    `first_name` VARCHAR(100) NULL,
    `last_name` VARCHAR(100) NULL,
    `phone` VARCHAR(32) NULL,
    `role` VARCHAR(30) NOT NULL DEFAULT 'customer',
    `status` VARCHAR(30) NOT NULL DEFAULT 'active',
    `email_verified_at` DATETIME(6) NULL,
    `last_login_at` DATETIME(6) NULL,
    `failed_login_count` INT NOT NULL DEFAULT 0,
    `locked_until` DATETIME(6) NULL,
    `mfa_enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `mfa_secret_reference` VARCHAR(255) NULL,
    `mfa_enrolled_at` DATETIME(6) NULL,
    `last_password_change_at` DATETIME(6) NULL,
    `metadata` JSON NOT NULL DEFAULT (JSON_OBJECT()),
    `preferred_locale` VARCHAR(20) NOT NULL DEFAULT 'en-AU',
    `timezone` VARCHAR(80) NOT NULL DEFAULT 'Australia/Melbourne',
    `deleted` DATETIME(6) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_users_email` (`email`),
    KEY `idx_users_password_reset_token` (`password_reset_token`),
    KEY `idx_users_role_status` (`role`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- @@STATEMENT_END@@

CREATE TABLE `contact_messages` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(32) NULL DEFAULT NULL,
    `subject` VARCHAR(255) NOT NULL,
    `message` TEXT NOT NULL,
    `is_read` TINYINT(1) NOT NULL DEFAULT 0,
    `created` DATETIME NOT NULL,
    `reference_number` VARCHAR(40) NULL,
    `customer_id` BIGINT UNSIGNED NULL,
    `user_id` INT NULL,
    `source` VARCHAR(30) NOT NULL DEFAULT 'web_form',
    `status` VARCHAR(30) NOT NULL DEFAULT 'new',
    `inquiry_type` VARCHAR(50) NULL,
    `product_id` BIGINT UNSIGNED NULL,
    `service_type_id` BIGINT UNSIGNED NULL,
    `preferred_reply_channel` VARCHAR(20) NULL,
    `consent_to_contact` TINYINT(1) NOT NULL DEFAULT 1,
    `captcha_provider` VARCHAR(50) NULL,
    `captcha_verified_at` DATETIME(6) NULL,
    `ip_hash` CHAR(64) NULL,
    `user_agent` VARCHAR(512) NULL,
    `assigned_to_user_id` INT NULL,
    `last_response_at` DATETIME(6) NULL,
    `resolved_at` DATETIME(6) NULL,
    `modified` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_contact_messages_reference` (`reference_number`),
    KEY `idx_contact_messages_status_created` (`status`, `created`),
    KEY `idx_contact_messages_assigned_status` (`assigned_to_user_id`, `status`),
    KEY `idx_contact_messages_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- @@STATEMENT_END@@
