name: CI

on:
  push:
    branches: [main, jiarui]
  pull_request:
    branches: [main, jiarui]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.2'
            dependencies: 'lowest'
          - php-version: '8.5'
            dependencies: 'highest'

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        ini-values: zend.assertions=1
        coverage: none

    - name: Composer install
      uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
      with:
        dependency-versions: ${{ matrix.dependencies }}
        composer-options: ${{ matrix.composer-options }}

    - name: Composer post install
      run: composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit
      run: vendor/bin/phpunit
      env:
        DATABASE_TEST_URL: sqlite://./testdb.sqlite

  coding-standard:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl
        coverage: none
        tools: cs2pr, phpstan:2.1

    - name: Composer install
      uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4

    - name: Composer validate
      run: composer validate --strict

    - name: Composer audit
      run: composer audit --locked --abandoned=fail

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --report=checkstyle | cs2pr

    - name: Run phpstan
      if: always()
      run: phpstan
      env:
        SECURITY_SALT: f76f1c8475585c46c6acd3ddcb8f5e0f15de524637bb4080a08c4afe7cfc9144
